version: "3.8"
services:
  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=cards
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data